name: despeckling_fans
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - matplotlib
  - numpy
  - scipy
  - pip
  - pip:
      - "jax[cuda12]"
      - rasterio
      - matlabengine
      - ipykernel