name: despeckling_merlin
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.13.3
  - matplotlib
  - gdal
  - pip
  - pip:
      - "jax[cuda12]"
      - rasterio
      - deepdespeckling
      - ipykernel