name: despeckling_speckle2void
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10
  - numpy
  - scipy
  - tensorflow-gpu==1.14.0
  - tensorboard==1.14.0
  - matplotlib
  - jupyter
  - keras==2.3.1
  - tifffile==2019.7.26.2
  - scikit-image
  - pillow
  - h5py==2.9.0
  - pip
  - pip:
      - "jax[cuda12]"
      - csbdeep==0.5.1