name: despeckling_sarcam
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - numpy
  - pandas
  - opencv
  - pillow
  - tqdm
  - pip
  - pip:
      - torch>=1.8.0
      - torchvision
      - torchsummary
      - ipykernel